script: |
  set -e

  echo "➡️ Go to home"
  cd ~

  echo "➡️ Ensure project exists"
  if [ ! -d "devops-webapp" ]; then
    git clone https://github.com/salan2022/devops-webapp.git
  fi

  cd devops-webapp

  echo "➡️ Update code"
  git pull origin main

  echo "➡️ Restart Docker"
  docker-compose down || true
  docker-compose up -d

  echo "✅ Deployment successful"
