name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: vboxuser
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "➡️ Go home"
            cd ~

            echo "➡️ Clone or update repo"
            if [ ! -d "devops-webapp" ]; then
              git clone https://github.com/salan2022/devops-webapp.git
            fi

            cd devops-webapp

            git pull origin main

            echo "➡️ Restart Docker"
            docker-compose down || true
            docker-compose up -d

            echo "✅ Deployment done"
